name: "Build and Test whole project"

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test the whole project
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install prerequisites
        run: sudo apt-get install -y python3 python3-pip cmake build-essential tree
      - name: visually control the code
        run: tree .
      - name: build the code
        run:  |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: notify user
        run: echo "Success!"
